let base = "http://www.w3.org/2001/XMLSchema#"

let build_iri fragment = base ^ fragment |> Iri.of_string

let any_uri = build_iri "anyURI"
let base64_binary = build_iri "base64Binary"
let boolean = build_iri "boolean"
let date = build_iri "date"
let dateTime = build_iri "dateTime"
let decimal = build_iri "decimal"
let double = build_iri "double"
let duration = build_iri "duration"
let float = build_iri "float"
let gDay = build_iri "gDay"
let gMonth = build_iri "gMonth"
let gMonthDay = build_iri "gMonthDay"
let gYear = build_iri "gYear"
let gYearMonth = build_iri "gYearMonth"
let hexBinary = build_iri "hexBinary"
let integer = build_iri "integer"
let notation = build_iri "NOTATION"
let q_name = build_iri "QName"
let string = build_iri "string"
let time = build_iri "time"
